#!/bin/bash

sudo cp /etc/hosts /etc/hosts.bak

echo "Modifying /etc/hosts to update IP resolutions."

sudo sed -i 's/^127\.0\.0\.1\s*localhost/127.0.0.2 localhost/' /etc/hosts
sudo sed -i '/^8\.8\.8\.8\s*facebook\.com/d' /etc/hosts
echo '8.8.8.8 facebook.com' | sudo tee -a /etc/hosts > /dev/null

echo "The /etc/hosts file has been updated:"
cat /etc/hosts
